### PR TITLE
Small group see leader

### LINKED ISSUE #258: Users should be able to see who is in charge of their small group

### PR DESCRIPTION
**Pull request by Istyatur**
Fixes #258

### CODE REVIEW

**Comment by agundy** [comment]
do you know what's up with these commits being funky and including stuff already on master?

**Comment by Istyatur** [comment]
No, other than its undoubtably a mistake of mine in the endless mysteries of git. I asked Seve about it and he said to put it up so he could take a look and see if anything needed to be done about it.

**Comment by agundy** [comment]
Sounds good. If he can't figure it out I'll take a look too

**Comment by Istyatur** [comment]
Why add a need fixing? there is no known problem that needs to be fixed, or a trace of one other than a fluke test which has passed the same code on a subsequent run.

**Comment by kmcnellis** [comment]
Its due to the odd commits included

**Comment by Istyatur** [comment]
might we merge this before new conflicts arise?

**Comment by Istyatur** [comment]
@seveibar  while there are the weird commits, the merges from master show no problems. and you assessment of the visual was roughly thats looks good, ready to get merged so...

**Comment by seveibar** [comment]
thanks for the follow up Alex, I think it's okay to get merged

**Pull request merged**
