### PR TITLE
Edit title of a project

### PR DESCRIPTION
**Pull request by vkr96**
Editing title should be finished

### CODE REVIEW

**Comment by kmcnellis** [comment]
Can you split the Added Donate Hyper-Link into a different pull request? Also be sure to add "fixes #159" so it automatically closes the issue upon merge.

**Comment by agundy** [comment]
I will split it up.

**Comment by agundy** [comment]
This was by far the worst merge conflict I have ever resolved. I am voting we try to merge commits faster next time. We still have a lot more coming up and we may have trouble merging them too. Someone should look over my work but I'm merging this ASAP. Notifications are being pulled into this too.

**Comment by vkr96** [comment]
Since it was not merged fast enough was that causing problems?

**Comment by agundy** [comment]
A tad. Not usually but we were touching a lot of stuff. We also added notifications on edits as opposed to throwing alerts and that was fun too. Mostly just my fault. Not yours @vkr96. Thanks @vkr96

**Pull request merged**
