### PR TITLE
added functionality to show attendants

### LINKED ISSUE #484: Should be able to get a full list of students who used each attendance code

### PR DESCRIPTION
**Pull request by yongabyte**
fixes #484

### CODE REVIEW

**Comment by kmcnellis** [comment]
This is a great first step! 

A small thing - the popup doesn't fade and collides when you open multiple days

screen shot 2016-10-25 at 12 30 03 pm

**Comment by kmcnellis** [comment]
Maybe we should make this a slide down list of people who attended, or color in the main people boxes when you hover over one of the attendance days?

**Comment by yongabyte** [comment]
wait, what???

**Comment by kmcnellis** [comment]
The current PR was good enough to merge. I'm doing a pretty big refactor of the attendance page, so we can revisit the style later

**Pull request merged**
