### PR TITLE
Profile page can't be edited fix

### LINKED ISSUE #108: Cannot modify user profile page
Getting errors like "Could not add tech" and "could not update bio" when trying to modify user profile

### PR DESCRIPTION
**Pull request by seveibar**
fixes #108

### CODE REVIEW

**Comment by agundy** [comment]
Just curious why this is needed?

**Comment by seveibar** [comment]
Some information about the user is loaded asynchronously (see issue #108)

**Comment by seveibar** [comment]
See issue #108, mongodb returns a buffer for the _id

**Comment by seveibar** [comment]
If you logged both sides of the equality before the save, you'd get this...

5cfff4sasdfeuthty    ===     '5cfff4sasdfeuthty'

**Pull request merged**
