### PR TITLE
Moved tech tags to a more logical place

### PR DESCRIPTION
**Pull request by agundy**
some basic formatting fixes and moved tech tags to their own box instead of floating below everything else.

### CODE REVIEW

**Comment by kmcnellis** [comment]
Related to #299 and #297

**Comment by seveibar** [comment]
for client side/display fixes we can probably speed up the process by including a screenshot (as a general note)

**Comment by kmcnellis** [comment]
+1

**Comment by agundy** [comment]
well review it without a screenshot for now. All you have to do is checkout the branch :P I want to get this in so that we can update.

**Comment by kmcnellis** [comment]
Still not a fan of the tech tags, but better than before. Fixes #297

**Comment by agundy** [comment]
This doesn't fix #297...

**Comment by kmcnellis** [comment]
It fixed it for me...

**Pull request merged**
