### PR TITLE
Added grunt seed command

### PR DESCRIPTION
**Pull request by agundy**
broke users and projects out into separate json files for easy additions. Also made it so adding a generator later wouldn't be too much additional work

### CODE REVIEW

**Comment by jfucci** [comment]
looks like mocha can't find the 'promise' module that you are trying to use. Should probably fix that test before we merge

**Comment by agundy** [comment]
added promise to the dependencies. should work now.

**Comment by agundy** [comment]
@jfucci any other concerns now that the tests are passing?

**Comment by kmcnellis** [comment]
Looks good!

**Pull request merged**
