### PR TITLE
Changed the input field on projects to have inline icon

### LINKED ISSUE #307: Improve search bar to not look like button
Something that looks like the search bar on https://github.com/rcos/Observatory3/issues would be ideal

### PR DESCRIPTION
**Pull request by gitcole**
Fixes  #307

### CODE REVIEW

**Comment by vkr96** [comment]
Could you post what issue number this closes

**Comment by kmcnellis** [comment]
This didn't fix an issue - just a thing that needed doing

**Comment by kmcnellis** [comment]
It fixes  #307

**Comment by kmcnellis** [comment]
Looks good!

**Pull request merged**
