### PR TITLE
Hide page buttons when filtered users are less than default page size

### LINKED ISSUE #521: Hide Page Numbers for search
screenshot from 2016-11-01 16-39-16

Hide the Arrows plz

### PR DESCRIPTION
**Pull request by jessamarie**
In progress. Started to add desired functionality. Moved search string filter to controller in order to be able to access the length of filtered array. 

fixes #521

### CODE REVIEW

**Comment by jessamarie** [comment]
Tested functionality with different default page sizes. Buttons are appropriately hiding when the number of searched users goes below page size. Ready to merge, I think.

**Comment by jessamarie** [comment]
@agundy can you take a look at this when you have some time?

**Comment by agundy** [comment]
oooh looks cool. WIll confirm

**Comment by agundy** [comment]
Looks great @jessamarie! Works smoothly and makes it look better.

**Comment by jessamarie** [comment]
@agundy cool, thanks!!

**Pull request merged**
