### PR TITLE
Working on Layout and design of pages

### PR DESCRIPTION
**Pull request by agundy**
Mostly iterative improvements to the site. We aren't well designed and continual improvements and refinement will hopefully leave us with a decent looking site. Screenshot shows the new layout of the main page in both mobile and desktop format. Let me know what you all think.
screenshot from 2016-12-11 23-45-47

### CODE REVIEW

**Comment by kmcnellis** [comment]
Can we see the updates screenshot?

**Comment by agundy** [comment]
What do you mean? I haven't pushed any updates since the screenshot

**Comment by kmcnellis** [comment]
Oh, weird. The formatting was just deceptive

**Comment by agundy** [comment]
@kmcnellis comfortable with these changes for now? Or any changes you want before merge?

**Comment by kmcnellis** [comment]
I believe suggestions were talked about on slack

**Pull request merged**
