### PR TITLE
Developers page updates

### PR DESCRIPTION
**Pull request by agundy**
- Now default to having a white background placeholder which fixes the
  moving asynch load of gravatars
- Adjusted the sizing of images on smaller screens

addresses #347

### CODE REVIEW

**Comment by jfucci** [comment]
looks like this failed due to a timeout... can someone else confirm this is just a travis issue? The code seems like it is fine

**Comment by agundy** [comment]
yea this is a travis issue. The one worked and the other did not. Trying to find a way to rerun the checks

**Comment by agundy** [comment]
Any opposition to me merging this?

**Comment by kmcnellis** [comment]
@agundy It looks good, but you should drop the resolution of the gravitars as well

**Comment by kmcnellis** [comment]
Also, I think 1 developer (full width, or with a small margin) looks better than 2 side by side on a small screen

**Comment by agundy** [comment]
I changed that because 1 developer means that you have to scroll through 50 to get to the next page. And the avatars are huge.

**Comment by kmcnellis** [comment]
2 side by side just looks odd, though.  Maybe try 3? or make sure there is some sort of margin

**Comment by agundy** [comment]
I'll revisit it

**Comment by agundy** [comment]
Updated!

**Pull request merged**
