### PR TITLE
can show attendance without fullscreen

### LINKED ISSUE #254: Small group attendance codes should be able to be seen by mentors without fullscreen
(for copy-pasting purposes)

### PR DESCRIPTION
**Pull request by nickkoul**
Made another button to choose to put the attendance code fullscreen
Fixes #254

### CODE REVIEW

**Comment by nickkoul** [comment]
Fixes #254

**Comment by kmcnellis** [comment]
You should take a look at the wording and workflow of the admin's class control ui (where big group codes are generated).  Try to make this about the same as that. (Generate a code, it gets shown on the screen (only seen by mentor and admins) and then the show full screen should be an option that is shown after a code is generated.)

**Comment by nickkoul** [comment]
I am a little confused about what you want changed.

 Currently the way it works is only an admin or mentor has a button to show attendance and that puts the code on the screen. When you press that button a 2nd button to make full screen is shown and you can either press that to go full screen or press the original button to hide the code and the full screen button is then hidden. 

Do you want it so that when you press the show attendance button the code is shown on the screen and then you can either press the button again to go full screen so it all works off of one button.

**Comment by kmcnellis** [comment]
Basically just UI/UX things to make it act more like the class control tab. 
You click the 'Generate Attendance Code' Button
screen shot 2015-12-02 at 2 59 04 pm
Then the attendance code is shown (Not sure there is a purpose to hiding it)
Then there is a Show Fullscreen or Show Attendance Code button to show full screen
screen shot 2015-12-02 at 2 59 12 pm

Should be pretty simple changes

**Comment by nickkoul** [comment]
Okay I changed it to work off of one button now

You have one button to show attendance

screenshot from 2015-12-02 16 50 48

After you press the button the code is displayed and you can choose to make fullscreen

screenshot from 2015-12-02 16 50 53

Fullscreen version of the code

screenshot from 2015-12-02 16 50 55

**Comment by kmcnellis** [comment]
Sorry for being nitpicky :disappointed:  Its the Show vs Generate attendance that concerns me - Because attendance is kinda a percent and its created when the first person clicks the button  (Currently in your pr, Show Attendance), we don't really want to make it look like there is always a code just waiting for them. Also, if there is another mentor, they should be able to see that there was a code generated, and that code shown without clicking on their page.  The full screen is good, though!

**Comment by kmcnellis** [comment]
Maybe the show/hide code could be another feature added to both attendance sites?

**Comment by kmcnellis** [comment]
(Also there are conflicts that should be resolved now)

**Comment by kmcnellis** [comment]
Awesome, thanks!

**Comment by nickkoul** [comment]
still trying to figure out the merge conflict

**Comment by kmcnellis** [comment]
I can take care of that this time

**Pull request merged**
