### PR TITLE
Deleted buttons that were redundant on sign-in and login page

### LINKED ISSUE #348: Register Page Log-In Button
Once the register page is filed out and the user clicks the 'Log in' button the email is not actually registered. On the Login Page says the given email is not registered. The user has to click the Register Button after filling out the register page instead of login. These buttons seem to be a toggle between the Login page and Register Page but is confusing which is the correct button to press after filling out the Registration Form.

### PR DESCRIPTION
**Pull request by vkr96**
Fixes #348

### CODE REVIEW

**Comment by vkr96** [comment]
Hey @agundy could you post here as to what changes you want to this PR

**Comment by agundy** [comment]
i'll just add a link on the bottom.

**Comment by kmcnellis** [comment]
This should have a similar layout to github's login - The reset password button should be across from the password title, and there should be a "New to RCOS? Create an account." link below on the login page (as a bootstrap button styled as a link)

**Comment by agundy** [comment]
screenshot from 2016-03-08 23-49-34
screenshot from 2016-03-08 23-49-55

Updated. See screenshots.

**Comment by kmcnellis** [comment]
Pulled in through #363

**Pull request closed without merging**
