### PR TITLE
Fix the developers page spacing

### LINKED ISSUE #191: Developers names aren't near picture
On the developers page the names are far enough from the bottom of the image that they look like they are above the image below. We should fix the spacing on this.

### PR DESCRIPTION
**Pull request by kmcnellis**
Fix developer's page to look correct on small screens and have better spacing

Fixes #191

### CODE REVIEW

**Comment by seveibar** [comment]
this adds a lot of code- the why can't the fix be done in a couple lines of bootstrap? The media widths are built in to bootstrap

**Comment by kmcnellis** [comment]
I also fixed a bunch of other ui problems on that page :)

**Comment by kmcnellis** [comment]
The code is a chunk that allows columns to be the same height.  Right now the  1 of 4 and Active developers toggle are not vertically aligned.  The chunk of css allows us to correctly align them

**Comment by kmcnellis** [comment]
http://www.minimit.com/articles/solutions-tutorials/bootstrap-3-responsive-columns-of-same-height

**Pull request merged**
