### PR TITLE
Overhaul project profile page

### PR DESCRIPTION
**Pull request by burkel24**
[check it out](http://imgur.com/4rkJ9Yo)

### CODE REVIEW

**Comment by agundy** [comment]
you may want to talk with @jfucci he has been working on a redesign of the project page and has a pr out that handles some changes too it.

**Comment by jfucci** [comment]
Sorry for ignoring this for so long. I haven't worked on the project page in a while... I was going for a more drastic overhaul than this but this works well for me at the moment, especially since I don't plan on working on the profile page in the near future. Before I merge I want to make sure that merging into the rss branch is what you want to do... I presume after this is merged you are going to merge that branch into master?

**Comment by kmcnellis** [comment]
Addresses  #12

**Comment by vkr96** [comment]
@agundy @kmcnellis should this still be an open pr...? I think we should discuss as a group how we want to restructure the project page since its a pretty big change

**Pull request closed without merging**
