### PR TITLE
Improve indentation & max width

### PR DESCRIPTION
**Pull request by kmcnellis**

### CODE REVIEW

**Comment by agundy** [comment]
don't like my PR? 😞

**Comment by kmcnellis** [comment]
Not that part of it. Plus the width vs max-width thing is real

**Comment by agundy** [comment]
my pr has the max-width property in it

**Comment by kmcnellis** [comment]
No, it has width

**Comment by agundy** [comment]
:shipit:

**Comment by kmcnellis** [comment]
event-description {
 +  *> img {
 +    width: 100%;
 +  }

**Pull request merged**
