### PR TITLE
Show smallgroup option to create if none

### PR DESCRIPTION
**Pull request by kmcnellis**
Missed this earlier

### CODE REVIEW

**Comment by agundy** [comment]
Why are you removing the loaded? Shouldn't we wait until the response loads and if it's a 4XX set the loaded = true. If you remove the loaded it will show a create until the small group loads

**Comment by kmcnellis** [comment]
Loaded was removed in #516 I'll see if it needs to be re-added instead

**Comment by kmcnellis** [comment]
I'll leave re-adding to a future PR. This is just to rectify the feature not working.

**Comment by agundy** [comment]
cool. Will merge

**Comment by kmcnellis** [comment]
ping

**Pull request merged**
