### PR TITLE
added user controller test #205

### LINKED ISSUE #205: Test for users successfully returning an array
Just like we check projects to see if the endpoint returns an array we should make sure the /api/users/ does too.

### PR DESCRIPTION
**Pull request by joshualu4**
server/api/user
fixed #205

### CODE REVIEW

**Comment by agundy** [comment]
you should be calling /api/users/ and this should work! Good start

**Comment by agundy** [comment]
Your initial commit is good. you just missed the end of the url,

**Comment by joshualu4** [comment]
Joshua Lu, Oscar Pullan. We did this

**Comment by vkr96** [comment]
@joshualu4 are you working on this?

**Comment by agundy** [comment]
Using this code with fixes in #344

**Pull request closed without merging**
