### PR TITLE
Initial notifications implementation

### LINKED ISSUE #80: Frontend Notifications API
Users should be able to see new events/notifications

### PR DESCRIPTION
**Pull request by seveibar**
Fixes #80

### CODE REVIEW

**Comment by agundy** [comment]
Can you fix the broken build? Looks like you forgot a dependency somewhere.

**Comment by agundy** [comment]
Found the problem. Add the dependency into the karma conf file for the test loading in phantom.

**Comment by kmcnellis** [comment]
note: requires a bower install

**Comment by agundy** [comment]
If you use the bower and karma file changes I checked into master this branch should pass the build

**Pull request merged**
