### PR TITLE
Project tech tags

### PR DESCRIPTION
**Pull request by Istyatur**

### CODE REVIEW

**Comment by seveibar** [comment]
@Istyatur we can't merge until this passes the build

**Comment by Istyatur** [comment]
wha? i didn't touch those functions. and i have no idea what mocha is.

**Comment by seveibar** [comment]
https://mochajs.org/

It's our testing framework, the original issue had a problem.

**Comment by Istyatur** [comment]
So... close and reopen? i can't fix a false bug.

**Comment by seveibar** [comment]
Are you sure it's false?

**Comment by agundy** [comment]
Re running the failed test. It may have just been a fluke/flaky test run.

**Comment by Istyatur** [comment]
seems like it was the test.

**Comment by jfucci** [comment]
Is there a reason this hasn't been merged yet?

**Comment by Istyatur** [comment]
There was a fluke travis ci test,  but as far as i know its good to go.

**Pull request merged**
