### PR TITLE
Display attendance information correctly on profile page and keep track of user's bonus days

### LINKED ISSUE #138: Display attendance information correctly on profile page

### LINKED ISSUE #228: Make it so that the user can only submit the day code once
Right now a user can submit the same code twice and an error is thrown that crashes the server.
The backtrace shows that line 360 in server/api/user/user.controller.js is where the error is thrown.

### PR DESCRIPTION
**Pull request by kmcnellis**
Look at the first 2 commits to see the pre-jshint changes.

Fixes #138 

also fixes #228

### CODE REVIEW

**Comment by seveibar** [comment]
eek! bonusAttendance should be a virtual! This will break attendance!

**Comment by seveibar** [comment]
we can detect bonusAttendance days from the ClassYear

**Comment by seveibar** [comment]
i.e. ClassYears keep track of bonusAttendance days, so you can reference a users attendance from bonusDays

**Comment by seveibar** [comment]
other than that- this is good refactor

**Comment by seveibar** [comment]
Small Group contains the fix for #228 already (it was lodged in one of the early commit messages)

**Comment by agundy** [comment]
I think we should try to do linting changes in separate pr's much cleaner and easier to merge worry free

**Comment by kmcnellis** [comment]
I was planning on it, but my editor did some by accident. Also, seve - fixing 228 it was a side effect of making the bonus days work. I'll refactor once your code is merged

**Comment by kmcnellis** [comment]
And for the bonus days - its cleaner so that activities that happen to be on the same day as a meeting can have a bonus code.  (Potentially we should also do that in general, so you can have more than one code per day)

**Comment by seveibar** [comment]
:+1: let's merge after small groups

**Comment by seveibar** [comment]
this WILL still break live site attendance- the result will be those who attended a bonus day will get a valid day of attendance

**Comment by vkr96** [comment]
@kmcnellis how is this going?

**Pull request closed without merging**
