### PR TITLE
Styling admin page and view bonus correctly

### PR DESCRIPTION
**Pull request by kmcnellis**

### CODE REVIEW

**Comment by agundy** [comment]
mentioned in person but don't like the past and current user distinction. makes it hard if you accidentally click a user to be past. Also should try to find a font awesome icon instead of an x

**Comment by gitcole** [comment]
There is a gylicon for that

**Comment by kmcnellis** [comment]
Changed it to have check boxes. Let me know what you think!

**Comment by kmcnellis** [comment]
screen shot 2016-04-15 at 10 42 37 am

**Comment by agundy** [comment]
i don't think you need to have the activate/deactivate text below the checkbox

**Comment by kmcnellis** [comment]
It is so that you can deactivate just 1 person immediately

**Comment by kmcnellis** [comment]
screen shot 2016-04-15 at 1 25 08 pm

**Comment by agundy** [comment]
Github links should open in a new tab. Also icons in the topbar should have title text to explain what they stand for, ie '+' > 'Bonus Days'

**Comment by agundy** [comment]
I don't think we should have the names centered

**Pull request merged**
