### PR TITLE
Added more advanced markdown editor

### PR DESCRIPTION
**Pull request by SaswatB**
For issue #639 

image
Edited on Dec 13, added new screenshot.

### CODE REVIEW

**Comment by yongabyte** [comment]
the full screen/ exit full screen button is weird. 
image
on mobile:
image

**Comment by vkr96** [comment]
why has this not been merged???

**Comment by yongabyte** [comment]
This is on me. #639 was opened by @aeksco and since he's on the team now, I was thinking he should be reviewer but I forgot to @ him nor to take a screenshot of the final view when I finished.

**Comment by aeksco** [comment]
@SaswatB Just saw this! I'll merge this in right now - fantastic work!

**Pull request merged**
