### PR TITLE
Fixed styling of top buttons and fixed #425 error with carousel

### LINKED ISSUE #425: Carousal Image Index buttons are out of the bounding box if user is not on project.
screenshot 2016-04-22 at 12 41 40 pm

### PR DESCRIPTION
**Pull request by agundy**
fixes #425

### CODE REVIEW

**Comment by kmcnellis** [comment]
The buttons now have a large gap.. 
screen shot 2016-09-27 at 11 11 09 am

**Comment by agundy** [comment]
trying to make them better because before they were all the way at the top above the project name. I'll play iwth it

**Comment by agundy** [comment]
I hate those buttons

**Comment by kmcnellis** [comment]
Can you fix these conflicts @agundy ?

**Pull request merged**
