### PR TITLE
Multiple repository support

### PR DESCRIPTION
**Pull request by jfucci**
Addresses #142. The way the project page shows multiple repos is not ideal right now I know, but I'm working on more drastic ui changes so it will be changed in a future pull request. We also need to look into database migration from repositoryUrl to repositories[].

### CODE REVIEW

**Comment by agundy** [comment]
screenshot from 2015-10-12 21 45 36 is this what it is supposed to look like? Doesn't look right imo.

**Comment by jfucci** [comment]
could i get a screenshot of what you think looks wrong?

**Comment by agundy** [comment]
I posted one in my last comment, maybe it's not viewable by email? The buttons are what look weird.

**Comment by agundy** [comment]
I would look to use dropdown buttons for showing multiple repos http://getbootstrap.com/components/#btn-dropdowns


—

**Comment by jfucci** [comment]
Oh sorry don't know why that wasn't showing up before... Also I forgot I had the urls like that before starting the overhaul. I'll fix just that repository button for this pull request.

**Comment by agundy** [comment]
could you make us a one off script for migrating the db from singular strings to the list before we merge this?

**Comment by jfucci** [comment]
where should I put the script? I have it written up

**Comment by agundy** [comment]
perhaps just make a scripts folder and put it in there for now, may be helpful for later if we need to do more upgrades.

**Comment by jfucci** [comment]
use the script as per standard mongo script usage... i.e.:
mongo <db name> scripts/migrateRepositoryUrlToRepositories.js

**Comment by kmcnellis** [comment]
This ready to go, @agundy @jfucci ?

**Comment by agundy** [comment]
It was good until something conflicted.

**Comment by jfucci** [comment]
fixed merge conflicts; should be good now

**Pull request merged**
