### PR TITLE
paginated developer pages and added them to browser history

### PR DESCRIPTION
**Pull request by jessamarie**

### CODE REVIEW

**Comment by vkr96** [comment]
Did this get code reviewed before the merge?

**Comment by agundy** [comment]
I had worked with her at RCOS today. Will confirm on master before deploying.

**Comment by jessamarie** [comment]
Sorry about that! For some odd reason I thought it had already been reviewed. Will be more careful next time.

**Comment by agundy** [comment]
No worries! We usually just try to get another set of eyes on it before it gets put on master to makes sure everything is good and we didn't miss any files or changes.

**Pull request merged**
