### PR TITLE
Project chooser on registration

### LINKED ISSUE #137: Default projects for new users
Dependent on #136 

New users get a choice to join a "Default" project.

### PR DESCRIPTION
**Pull request by zlalvani**
fixes #137

### CODE REVIEW

**Comment by vkr96** [comment]
@zlalvani the checks have failed

**Comment by zlalvani** [comment]
there could be a problem with the travis tests
```
Running "mochaTest:src" (mochaTest) task

>> Mocha exploded!

>> Error: Cannot find module 'bson'

>>     at Function.Module._resolveFilename (module.js:336:15)

>>     at Function.Module._load (module.js:278:25)

>>     at Module.require (module.js:365:17)

>>     at require (module.js:384:17)

>>     at Object.<anonymous> (/home/travis/build/rcos/Observatory3/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection.js:10:16)

>>     at Module._compile (module.js:460:26)

>>     at Object.Module._extensions..js (module.js:478:10)

>>     at Module.load (module.js:355:32)

>>     at Function.Module._load (module.js:310:12)

>>     at Module.require (module.js:365:17)

Warning: Task "mochaTest:src" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by vkr96** [comment]
@zlalvani travis has now passed?

**Comment by kmcnellis** [comment]
I re-ran the check.

**Comment by zlalvani** [comment]
Is this gonna be merged?

**Comment by jfucci** [comment]
Any reason to not merge this? It works well enough for me... just in the future it could use a couple visual tweaks and should be made accessible from other parts of the website. But this pr could be merged now.

**Comment by kmcnellis** [comment]
@jfucci Go ahead and merge if it looks good

**Pull request merged**
